/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Clan = IDL.Record({
  'id' : IDL.Text,
  'tag' : IDL.Text,
  'members' : IDL.Vec(IDL.Principal),
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'inviteCode' : IDL.Text,
});
export const PlayerProfile = IDL.Record({
  'username' : IDL.Opt(IDL.Text),
  'totalHeadshots' : IDL.Nat,
  'totalShots' : IDL.Nat,
  'totalRounds' : IDL.Nat,
  'currentLevel' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'totalKills' : IDL.Nat,
});
export const ChatType = IDL.Variant({ 'clan' : IDL.Text, 'global' : IDL.Null });
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'authorUsername' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'chatType' : ChatType,
  'authorPrincipal' : IDL.Principal,
});
export const ScoreEntry = IDL.Record({
  'wave' : IDL.Nat,
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});
export const SessionStats = IDL.Record({
  'shots' : IDL.Nat,
  'headshots' : IDL.Nat,
  'kills' : IDL.Nat,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Clan, 'err' : IDL.Text })],
      [],
    ),
  'getAllClans' : IDL.Func([], [IDL.Vec(Clan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClan' : IDL.Func([IDL.Text], [IDL.Opt(Clan)], ['query']),
  'getClanMessages' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(ChatMessage), 'err' : IDL.Text })],
      ['query'],
    ),
  'getGlobalMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getHighScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getMyClan' : IDL.Func([], [IDL.Opt(Clan)], ['query']),
  'getOrCreateProfile' : IDL.Func([], [PlayerProfile], []),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(PlayerProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinClanByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Clan, 'err' : IDL.Text })],
      [],
    ),
  'leaveClan' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
  'sendClanMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
      [],
    ),
  'sendGlobalMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
      [],
    ),
  'setUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Principal, SessionStats],
      [PlayerProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Clan = IDL.Record({
    'id' : IDL.Text,
    'tag' : IDL.Text,
    'members' : IDL.Vec(IDL.Principal),
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'inviteCode' : IDL.Text,
  });
  const PlayerProfile = IDL.Record({
    'username' : IDL.Opt(IDL.Text),
    'totalHeadshots' : IDL.Nat,
    'totalShots' : IDL.Nat,
    'totalRounds' : IDL.Nat,
    'currentLevel' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'totalKills' : IDL.Nat,
  });
  const ChatType = IDL.Variant({ 'clan' : IDL.Text, 'global' : IDL.Null });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'authorUsername' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'chatType' : ChatType,
    'authorPrincipal' : IDL.Principal,
  });
  const ScoreEntry = IDL.Record({
    'wave' : IDL.Nat,
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  const SessionStats = IDL.Record({
    'shots' : IDL.Nat,
    'headshots' : IDL.Nat,
    'kills' : IDL.Nat,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Clan, 'err' : IDL.Text })],
        [],
      ),
    'getAllClans' : IDL.Func([], [IDL.Vec(Clan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClan' : IDL.Func([IDL.Text], [IDL.Opt(Clan)], ['query']),
    'getClanMessages' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(ChatMessage), 'err' : IDL.Text })],
        ['query'],
      ),
    'getGlobalMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getHighScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getMyClan' : IDL.Func([], [IDL.Opt(Clan)], ['query']),
    'getOrCreateProfile' : IDL.Func([], [PlayerProfile], []),
    'getProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinClanByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Clan, 'err' : IDL.Text })],
        [],
      ),
    'leaveClan' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
    'sendClanMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
        [],
      ),
    'sendGlobalMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
        [],
      ),
    'setUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Principal, SessionStats],
        [PlayerProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };