/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlayerProfile {
  'totalHeadshots' : bigint,
  'totalShots' : bigint,
  'totalRounds' : bigint,
  'currentLevel' : bigint,
  'totalPoints' : bigint,
  'totalKills' : bigint,
}
export interface ScoreEntry {
  'wave' : bigint,
  'score' : bigint,
  'playerName' : string,
}
export interface SessionStats {
  'shots' : bigint,
  'headshots' : bigint,
  'kills' : bigint,
  'points' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHighScores' : ActorMethod<[], Array<ScoreEntry>>,
  'getOrCreateProfile' : ActorMethod<[], PlayerProfile>,
  'getProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[PlayerProfile], undefined>,
  'submitScore' : ActorMethod<[string, bigint, bigint], undefined>,
  'updateProfile' : ActorMethod<[Principal, SessionStats], PlayerProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];