/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlayerProfile = IDL.Record({
  'totalHeadshots' : IDL.Nat,
  'totalShots' : IDL.Nat,
  'totalRounds' : IDL.Nat,
  'currentLevel' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'totalKills' : IDL.Nat,
});
export const ScoreEntry = IDL.Record({
  'wave' : IDL.Nat,
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});
export const SessionStats = IDL.Record({
  'shots' : IDL.Nat,
  'headshots' : IDL.Nat,
  'kills' : IDL.Nat,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHighScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getOrCreateProfile' : IDL.Func([], [PlayerProfile], []),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(PlayerProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Principal, SessionStats],
      [PlayerProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlayerProfile = IDL.Record({
    'totalHeadshots' : IDL.Nat,
    'totalShots' : IDL.Nat,
    'totalRounds' : IDL.Nat,
    'currentLevel' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'totalKills' : IDL.Nat,
  });
  const ScoreEntry = IDL.Record({
    'wave' : IDL.Nat,
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  const SessionStats = IDL.Record({
    'shots' : IDL.Nat,
    'headshots' : IDL.Nat,
    'kills' : IDL.Nat,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHighScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getOrCreateProfile' : IDL.Func([], [PlayerProfile], []),
    'getProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Principal, SessionStats],
        [PlayerProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };